% Pentagonal numbers are generated by the formula, Pn=n(3n?1)/2. The first
% ten pentagonal numbers are:
% 
% 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
% 
% It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their
% difference, 70 ? 22 = 48, is not pentagonal.
% 
% Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
% difference is pentagonal and D = |Pk ? Pj| is minimised; what is the
% value of D?
% 
%   
% A: 5482660
% 
% P_2167  - P_1020  =
% 7042750 - 1560090 = 5482660 = P_1912
% 7042750 + 1560090 = 8602840 = P_2395
%
% Very inefficient brute force search based on considering the pentagonal
% numbers in order as possible differences.  Should be a better way.  This
% had to be run on a very fast machine ...
%

        
function prob_044

done = 0;
nDiff = 0;

while ~done
  
  nDiff = nDiff + 1;
  disp(nDiff)
  
  pentDiff = nDiff * ( 3 * nDiff - 1) / 2;
  
  
  
  nMax = 1 + floor((pentDiff + 2) / 3);
  
  validPents = (1:nMax) .* (3 * (1:nMax) - 1) / 2;
  
  for n1 = 1:nMax-1
    pent1 = validPents(n1);
    
    for n2 = n1+1:nMax
      pent2 = validPents(n2);
      
      currDiff = pent2 - pent1;
      if currDiff > pentDiff
        break;
      end
      
      if currDiff == pentDiff
        % Check if their sum is a pentagonal number.
        temp = pent1 + pent2;
        temp = (1/6) * (1 + sqrt(1 + 24 * temp));
        temp = abs(temp - round(temp));
        if  temp < eps
          done = 1;
          break;
        end
        
      end
    end
    
    if done
      break;
    end
    
  end
  
end

return